### ISSUE TITLE
RFC: replacing telepath

### ISSUE THREAD

**Issue by marcinczenko** [identity-box/identity-box#37]
Telepath is a centralized service, currently serving three purposes:

1. establishing connection between browser and Identity App - this enables web application to perform encryption/decryption and retrieving selected information related to user's identities from user's Identity App.

2. establishing connection between user's Identity App with user's Identity Box (eg. associating Identity Box with user's Identity App, creating/deleting identities (DIDs), creating/restoring backups, resolving other DIDs.

3. establishing connection between web-application and the associated service-provider's Identity Box. This web-application to resolve identities needed to perform the provided service.

To facilitate these tasks, Telepath uses an underlying Queuing Service. Queuing Service is a centralized service, currently hosted on Zeit.

> Queuing Service is a regular node server - a _continuously running server_ as defined in Zeit's vocabulary. Zeit used to support continuous server in Zeit Now 1.0 project deployment but it has been announced that Zeit Now 1.0 project will be completely abandoned by 7th August. So, by that time, we either move our Queuing Service, elsewhere, we rewrite so that it can use Zeit API functions, or we make it a true P2P and we do not need any centralized deployment any more.
Below some dates announced by Zeit:
>
> - 3rd of April 2020: ZEIT announces the deprecation of the ZEIT Now 1.0 platform.
> - 1st of May 2020: Creating new ZEIT Now 1.0 deployments will be prevented.
> - 7th of August 2020: All ZEIT Now 1.0 deployments will be deleted.

In this RFC we allow everyone to contribute to how the replacement of the Telepath should work by sharing their thought, needs, and observations. Based on this discussion a relevant service will be implemented and adopted by all Identity Boxes.

**Comment by marcinczenko** [comment]
I start with some comments we shared on other channels, so that they do not get lost. They are relevant, but they are not intended to disqualify new directions and opinions.

**Comment by marcinczenko** [comment]
A `DID` is in principle a `peer-id`, or it would be more appropriate to say that a `peer-id` is _base58 encoded multihash of ProtoBuf encoding of PKIX representation of JWK object format_ (https://github.com/Charterhouse/dids-for-cogito#publishing-1st-version-of-the-did-document). In other words every IPNS name, and so indirectly every Identity Box DID is compatible with `peer-id`. More specifically, every node has its own peerId, which is not being currently used as DID so, it could be used to uniquely identify a box and so maybe it could be used as a base for unique "telepath" endpoint. IdentityBox already has functionality that marshals and unmarshals ipfs keys (which are the same as in libp2p) for the purpose of creating/restoring backups. You can find it at: https://github.com/identity-box/identity-box/blob/660b2379c2dbeaa3970c05200336148bfae28146/workspaces/idservice/src/identity/IdentityProvider.js#L108.

**Comment by marcinczenko** [comment]
Semantically, a `peer-id` does not exist in a vacuum. It is related to something - to a public key, and this is one is related to some private key. I am not sure how the whole ipfs stack is constructed, but all these keys are crucial in ipfs to validate authenticity of the nodes connecting to each other. The node is identified with its peerId and if it does not have access to the corresponding (private) key, then it cannot establish connection. I am not sure if this part is already at the level of libp2p, but it may be something to take into account. If this would be the case, then providing just a random id as a channel id would not work. It is also possible to separate the mechanism used by libp2p to maintain connectivity, from a logical channel id applied on top of the already established communication channel. When I need to apply it to Identity Box as it is now, I may need to revise some of my assumptions, but now I cannot easily decide what is the right path. Still creating something sufficiently generic and more importantly with a well documented context, may help to build something on top of it or to revise the assumptions if needed. I probably should not even mention, that current telepath in identity box is more than just a p2p channel - I would describe it as a multiplexing channel - it allows more than just two peers to talk via one logical channel using the same channel id and channel key without interfering with each other (although peers use something called clientId/service PointId to facilitate that) - so it is still p2p, but many p2p connection can be established on one logical telepath channel. I call it a service channel in the documentation and the reason for it to exist is to enable multiple clients to connect to one server (used in hush-hush). So, not easy (wink).
<https://teams.microsoft.com/l/message/19:a840702fb3684d66a04633a99815a544@thread.skype/1585685317292?tenantId=1a407a2d-7675-4d17-8692-b3ac285306e4&amp;groupId=0b6bca22-4718-4a2f-a155-51a2b4368525&amp;parentMessageId=1585659046524&amp;teamName=Digital Trust&amp;channelName=General&amp;createdTime=1585685317292>

**Comment by marcinczenko** [comment]
It is also important to realize that current telepath in identity box is more than just a p2p channel - I would describe it as a multiplexing channel - it allows more than just two peers to talk via one logical channel using the same channel id and channel key without interfering with each other (although peers use something called clientId/service PointId to facilitate that) - so it is still p2p, but many p2p connection can be established on one logical telepath channel. I call it a service channel in the documentation and the reason for it to exist is to enable multiple clients to connect to one server (used in hush-hush).

**Comment by marcinczenko** [comment]
One of the potential choices for the Telepath replacement is to use libp2p. This sounds appealing, as IPFS and related technologies are already present in Identity Box. One of the convincing factors, is that libp2p supports creating a P2P node in a browser. This seems to be facilitated using [js-libp2p-webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star). The problem is that, following https://github.com/libp2p/js-libp2p/issues/385, js-libp2p-webrtc-star was never meant to be used in production. I am also a bit confused with the documentation about how to use external randezvous point.

Take the following example:

```javascript
const WStar = require('libp2p-webrtc-star')
const multiaddr = require('multiaddr')
const pipe = require('it-pipe')
const { collect } = require('streaming-iterables')

const addr = multiaddr('/ip4/188.166.203.82/tcp/20000/wss/p2p-webrtc-star/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSooo2a')

const ws = new WStar({ upgrader })

const listener = ws.createListener((socket) => {
  console.log('new connection opened')
  pipe(
    ['hello'],
    socket
  )
})

await listener.listen(addr)
console.log('listening')

const socket = await ws.dial(addr)
const values = await pipe(
  socket,
  collect
)

console.log(`Value: ${values.toString()}`)

// Close connection after reading
await listener.close()
```

The address in:

```javascript
const addr = multiaddr('/ip4/188.166.203.82/tcp/20000/wss/p2p-webrtc-star/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSooo2a')
```

seems to be an address of another node that I want to connect to. But how do I actually specify which randezvous server is supposed to be used?

I assume that each Identity Box, would have to run its own rendezvous server and share its url as part of the telepath channel description?

And if we follow above mentioned https://github.com/libp2p/js-libp2p/issues/385, what then?

**Comment by svdo** [comment]
Please note that I'm currently exploring the possibilities provided by libp2p by building HyperPath, a P2P version of TelePath. See: https://github.com/identity-box/hyperpath.

**Comment by marcinczenko** [comment]
obsolete
